### ISSUE TITLE
Full name of the foundation is not readable anywhere on openssf.org on mobile

### ISSUE THREAD

**Issue by mgalgs** [ossf/community#20]
This report is for the openssf.org homepage. I wasn't sure where to submit it, please let me know if there's a better place.

The current openssf.org homepage looks pretty good on mobile, except for the fact that nowhere on the page can you see the full name of the foundation. Although the acronym expansion is in the logo in the navbar, the text is too small to read without zooming in:

![IMG_3795](https://github.com/ossf/community/assets/152014/5066f322-54cf-47fc-8e1a-3807ec435f79)

In light of the recent `xz` security vulnerability there could be another surge in interest in security concerns in the open source community, similar to Heartbleed, which led to the creation of the Core Infrastructure Initiative, the precursor to the OSSF. So it's more important now then ever to put out effective branding that conveys trust and professionalism.

**Comment by presidentoor** [comment]
We have made the text slightly larger.

**Comment by mgalgs** [comment]
Still illegible in the logo on mobile, but the acronym is now expanded in the sub-hero, so not such an issue anymore. Thanks!

![image](https://github.com/ossf/community/assets/152014/064b9756-c882-4745-bb6d-34e5a4a3d709)
